### ISSUE TITLE
mount.nfs: remote share not in 'host:dir' format

### ISSUE THREAD

**Issue by KlugFR** [grufocom/vee-mail#1]
Hello.

I've made a quick try of the script on an Ubuntu 18.04 server.

Veeam Agent was setup to backup to /veeam, that is an NFS mount to another server.
It was setup to a "Local destination" not to a "Shared folder".

It seems the scripts sees the NFS mount and tries to mount it (as a tmp folder).
This gives an error:
```
mount.nfs: remote share not in 'host:dir' format
umount: /tmp/tmp.7aXngP8vHa: not mounted.
```

It tries to mount the target (/veeam) as a source for the tmp-mount.
This doesn't work, hence the error.

After changing the configuration of the backup (to a shared folder) in the configuration, no more error.

Backup is scheduled for tonight, I'll check if it still works correctly (with the shared folder) and if I'm getting the whole stats.

**Comment by grufocom** [comment]
Hi,

"local destination" is for local attached hard disks.
"shared folder" is for a network location - your nfs mount is a "shared folder" in veeam terms. ;-)

with that setting (shared folder) your backup should run and the info mail will arrive.
at the moment vee-mail does not work with local destinations, I'm thinking of integrating it.

**Comment by grufocom** [comment]
could you please try the version 0.5.13 which I just uploaded - it should also work with local device setting!

**Comment by KlugFR** [comment]
Hi.

Backup went well (from "local storage" to "shared folder").

I've juste deployed the new version of the script, no more error.
Here with debug on:
```
STARTTIME: 1597100401, ENDTIME: 1597100905, STATE: 6, JOBID: {b6a58b77-1a3d-49ff-8231-e2958e0620a7}
DETAILS: <ProgressDetails total_size="2276325326848" total_used_size="675263016960" processed_data_size_bytes="675264065536" read_data_size_bytes="2672820224" transferred_data_size_bytes="1018803323" processing_speed="6919725" source_read_load="87" source_processing_load="12" network_load="0" target_write_load="13" network_throttling_enabled="false" repository_throttling_enabled="false" />
TARGET: , FST: , LOGIN: , DOMAIN:
```

**Comment by grufocom** [comment]
thanks for testing and reporting back!

**Comment by KlugFR** [comment]
You might  want to reopen this one: since the new version, no more email is sent.

Line 125 should be:
`if [ !"$1" == "--bg" ]; then`
while it's currently:
`if [ ! "$1" == "--bg" ]; then`

Something added a space after the `!`, as a result the program exists (and no mail sent).

**Comment by grufocom** [comment]
The space after the "!" has always been there, that is not the reason why you haven't got an email.
At linie 125 the scripts checks if it's started in background-mode, and if not so it restarts itself in background mode. Then it waits 30 seconds before trying to send an email.
So maybe you have just waited not long enough?! :-)
Please check that, after that exit the script should run in background - use "ps -ef|grep vee-mail.sh" to see if it is still running.

**Comment by KlugFR** [comment]
Oups.

It does work, sorry 8-)

I've tried again, the script relaunches in background-mode and I eventually get my mail.
```
root@new-files:~# ps aux |grep vee
root      1180  0.0  0.7 1229972 124192 ?      Sl   Jul24   7:21 /usr/sbin/veeamservice --daemonize --pidfile=/var/run/veeamservice.pid
root      1817  0.0  0.0  11592  3096 pts/0    S    15:18   0:00 /bin/bash /opt/vee-mail/vee-mail.sh --bg
root      1862  0.0  0.0  13132   968 pts/0    S+   15:19   0:00 grep --color=auto vee
root      6762  0.0  0.0      0     0 ?        S    Jul24   0:03 [veeamsnap_log]
```

I guess I was too impatient.

The mail contains all the data (including the NFS mountpoint size) as soon as I unmount the mount I was using until then.

Thanks a lot.

**Comment by grufocom** [comment]
great that it works now, i hope you enjoy this little script! :-)
