### ISSUE TITLE
vee-mail fails with: sed: -e expression #27, char 21: unterminated `s' command

### ISSUE THREAD

**Issue by Cantello** [grufocom/vee-mail#12]
I recently re-installed an Ubuntu machine that had backups taken by veeam Agent and the status emails were sent by vee-mail -worked like a charm. However, after reinstalling, the vee-mail script always gives the following error message and sends an empty email:

    sed: -e expression #27, char 21: unterminated `s' command

The dependencies are installed, the script is run with sudo and the debug output is as follows:

    user@ubuntu:/opt/vee-mail$ sudo ./vee-mail.sh -bg
    STARTTIME: 1606398767, ENDTIME: 1606398771, STATE: 6, JOBID: {00000000-0000-0000-0000-000000000000}
    DETAILS: <ProgressDetails total_size="0" total_used_size="0" processed_data_size_bytes="0" read_data_size_bytes="0" transferred_data_size_bytes="0" processing_speed="0" source_read_load="0" source_processing_load="0" network_load="0" target_write_load="0" network_throttling_enabled="false" repository_throttling_enabled="false" />
    TARGET: , FST: , LOGIN: , DOMAIN: 
    PROCESSED: 0 GB, READ: 0 GB, TRANSFERRED: 0
    SPEED: 0, SOURCELOAD: 0, NETLOAD: 0, TARGETLOAD: 0
    DURATION: 00:00:04, START: Thursday, 26 November 2020 13:52:47, END: Thursday, 26.11.2020 13:52:51, STIME: 13:52:47, ETIME: 13:52:51
    ERRLOG:
    HN: UBUNTU
    STAT: Success
    BGCOLOR: #00B050
    START: Thursday, 26 November 2020 13:52:47
    SUCCESS: 1
    ERROR: 0
    WARNING: 0
    STIME: 13:52:47
    ETIME: 13:52:51
    READ: 0 GB
    TRANSFERRED: 0 MB
    DURATION: 00:00:04
    PROCESSED: 0 GB
    BOTTLENECK:
    ERRLOG:
    SPEED: 0
    TARGET:
    FST:
    LOGIN:
    DOMAIN:
     DEVUSEP: Use%
    0%
    1%
    25%
    0%
    0%
    0%
    100%
    100%
    100%
    100%
    100%
    100%
    100%
    9%
    69%
    7%
    4%
    7%
    13%
    25%
    25%
    25%
    25%
    25%
    25%
    25%
    25%
    25%
    25%
    0%
    0%
    sed: -e expression #27, char 21: unterminated `s' command

The last backup jobs have not in fact taken 4 seconds as indicated above but ~5 minutes as indicated by ´sudo veeam´. Also, it terminated with ´State: Warning´ instead of `Success` as listed here.

Any idea what could cause this? Using 0.5.26 by the way.

**Comment by Cantello** [comment]
Just after giving it one last try it appears to work again. I have not (knowingly) changed anything, just reviewing all config files.

Happy to report that I got sent a status email with all the correct data and layout.
:-)

**Comment by grufocom** [comment]
Good to hear that it works again! :-)
