### ISSUE TITLE
Restspeicherplatz bei SMB wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by hauetaler** [grufocom/vee-mail#15]
Beim Speichern auf einem SMB-Share wird der Speicherplatz nicht angezeigt (0.5.27). Der Debug-Modus zeigt, dass $FST den Wert "smb" und nicht "cifs" enthält.

**Comment by grufocom** [comment]
Kannst du das bitte mit der Version 0.5.28 prüfen?
Ich habe den Test um "smb" als Wert erweitert.

**Comment by hauetaler** [comment]
Da sind noch ein paar Slashes zuviel...

mount.cifs: bad UNC (////xx.xx.xx.xx/sicherung/Backup-VHost01/)
umount: /tmp/tmp.feYt4PE1vm: not mounted.

**Comment by grufocom** [comment]
OK, da gab's wohl eine Anpassung mit der letzten Version vom veeam - ich habe in der Version 0.5.29 was eingebaut das die überflüssigen "/" am Anfang entfernt.
Kannst du's bitte noch einmal testen?!

**Comment by grufocom** [comment]
Super, freut mich - danke für's Testen! :-)
