### ISSUE TITLE
No field to specify SMTP server

### ISSUE THREAD

**Issue by i486dx266** [grufocom/vee-mail#17]
The config file has no field to specify SMTP server, which is essential to be able to send mail on systems where sendmail is not installed. Anonymous on port 25 would be a good start. If it's possible to add that it would be a life saver for those of us who are under a company policy to not have sendmail on any system.

**Comment by grufocom** [comment]
Hi, you do not have to install sendmail itself - I use nullmailer as sendmail replacement.
Do you have bsd-mailx or anything like that on your system?
How do you get your system mails like errors from cron-jobs?
