### ISSUE TITLE
All is configure but no email was send

### ISSUE THREAD

**Issue by herken** [grufocom/vee-mail#2]
Hello  !

i configured the script on my Debian Strech. I configured Exim4 and email are send without any error but when i execute the script, i have just that : 

`root@PTCDEB-PROXY:/opt/vee-mail# bash vee-mail.sh
STARTTIME: 1597870801, ENDTIME: 1597870862, STATE: 6, JOBID: {a0a3cd38-1b39-4b28-86ef-95b7231cf62d}
DETAILS: <ProgressDetails total_size="17176723456" total_used_size="5232717824" processed_data_size_bytes="5232717824" read_data_size_bytes="4972347392" transferred_data_size_bytes="26472492" processing_speed="114856033" source_read_load="78" source_processing_load="88" network_load="0" target_write_load="88" network_throttling_enabled="false" repository_throttling_enabled="false" />
TARGET: 192.168.0.100/home, FST: cifs, LOGIN: veeam, DOMAIN: 
root@PTCDEB-PROXY:/opt/vee-mail# `

What's wrong? Seems that it can read data from the job but after that, nothing.

I modified DEBUG to 1 in config and in the vee-mail.sh but i don't have more information. 
All script is copied in /opt/vee-mail/

Thank you!

**Comment by KlugFR** [comment]
What is in your exim log (/var/log/mail.*)?

**Comment by grufocom** [comment]
please try the latest version!

**Comment by grufocom** [comment]
closed due to inactivity

**Comment by herken** [comment]
hello sorry i don't see notification about this issue ! I will try last version

**Comment by herken** [comment]
All works with last version, thank you !
