### ISSUE TITLE
using curl instead of sendmail

### ISSUE THREAD

**Issue by Domochip** [grufocom/vee-mail#25]
Hi,

I need to send the mail directly to an internal SMTP server.
I've found that curl can send mail directly using the same file format you implemented.

I replaced the sendmail call by this line : 
` curl --url 'smtp://192.168.X.X:25' --mail-from $EMAILFROM --mail-rcpt $EMAILTO --upload-file $TEMPFILE`

`--ssl-reqd` option allows usage of TLS
`--user 'username:password'` option allows authentication
etc

Do you still want to keep sendmail? If yes, are you interested in a Pull Request with a configuration allowing usage of curl instead of sendmail?

**Comment by grufocom** [comment]
Hi Domochip,
did not know that curl was capable of this. :-)
A pull request to use it as an option would be welcome!
Regards
Manfred

**Comment by Domochip** [comment]
Do you think that removing sendmail from the script is interesting?
(config need to be completed so it will be a breaking change)

**Comment by grufocom** [comment]
I don't think so - most systems have a working sendmail installed, curl is an option.

**Comment by Domochip** [comment]
ok

**Comment by grufocom** [comment]
you did the job! ;-)

**Comment by grufocom** [comment]
hi domochip, this does not work with starttls - I get curl: (67) login denied when I try to login into a mailserver which uses starttls and port 587. maybe curl only support ssl and not starttls?

**Comment by Domochip** [comment]
mm, error 67 may be related to incorrect login/password.
could you share more details regarding settings : 
- did you used an smtps://... uri
- did you enabled STARTTLS (CURLSTARTTLS=1)
- if you used a public provider, could let me know which one (Gmail, outlook.com, ...)

**Comment by grufocom** [comment]
I had no "s" in my url.
but with "s" I get this error message:
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

it is not a public provider, it is my private mail server.
I think smtps is just for ssl with port 467, port 587 and starttls should use a smtp url.

**Comment by Domochip** [comment]
by default curl validate mail server certificate (including the certificate sent by STARTTLS), does this one is approved by your client machine?
If it's not, you can give it a try using the CURLINSECURE=1 option

**Comment by grufocom** [comment]
the server uses an official certificate

the certificate is validated, there seems to be a problem with the authentication. maybe it's the special character in the password - "!" don't seem to be so well tolerated.
I think the user/password string should stay between single quotes.

**Comment by Domochip** [comment]
made https://github.com/grufocom/vee-mail/pull/34 to solve this issue :-)

**Comment by grufocom** [comment]
solved it! :-)
thx
