### ISSUE TITLE
vee-mail and old distros

### ISSUE THREAD

**Issue by KlugFR** [grufocom/vee-mail#3]
Hello, me again 8)

I've tried vee-mail with CentOS6 and I had issues.

The first one is about sqlite: needed version is 3.7 while the OS version is 3.6.
Maybe you could add is in the readme file?

Work around is simple: download sqlite3.7 and set it up.

What I did:
- download 3.7 binary for linux from https://sqlite3.org
- unzip the file somewhere and copy sqlite3 binary in the vee-mail folder (/opt/vee-mail for example)
- install x86 needed libraries (because the version downloaded from sqlite3.org is 32 bits): `yum -y install glibc.i686 zlib.i686`
- replace in vee-mail.sh the calls to sqlite3 to calls to /opt/vee-mail/sqlite3

Second issue is about the template: I'm getting a blank mail (but headers).
After digging in debug mode (see #4), I ended up with finding  a sed error: `sed: -e expression #30, char 19: unknown option to `s'` 
It's about the last expression, it seems to be related to sed 4.2.1 and expression (because of the percentage in the remplacement).
I don't have a work around (yet) for this.

If you remove the last expression, the email is OK except the Disk Use%  (not replaced).

**Comment by KlugFR** [comment]
Actually, not sure it's really about last expression (and the percentage).

Once the last expression is disabled (removed), here's the email content:
![veemail](https://user-images.githubusercontent.com/6048396/91643995-5c8c7b00-ea38-11ea-92fa-b1bd6d309bb5.jpg)

The problem might be in parsing the mountpoint.

**Comment by grufocom** [comment]
tried to fix that with the latest version.
what does "df -h" of your mountpoint look like?

**Comment by grufocom** [comment]
I added the comment for sqlite 3.7 to the readme file - thx!

**Comment by KlugFR** [comment]
Hello.

"df -h" looks normal on this old server.
```
[root@servr ~]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_server-lv_root
                       50G   42G  5.3G  89% /
tmpfs                 7.8G     0  7.8G   0% /dev/shm
/dev/sda1             477M  139M  313M  31% /boot
/dev/sdb1              99G   68G   26G  73% /home2
```

**Comment by grufocom** [comment]
your "dh -h" does not show the backup mountpoint - does it?
that's the one I am interested in ;-)

**Comment by KlugFR** [comment]
Ah ah, right.
I forgot to mount it before "df -h".

However, it seems to be the same two lines issues (because mountpoint is long).

```
[root@server ~]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_quitelongtrueservername-lv_root
                       50G   42G  5.2G  89% /
tmpfs                 7.8G     0  7.8G   0% /dev/shm
/dev/sda1             477M  139M  313M  31% /boot
/dev/sdb1              99G   59G   35G  63% /home2
192.168.xx.yyy:/mnt/Backup/VM/Veeam/server.domain.tld
                       30T   62G   30T   1% /mnt
```

**Comment by grufocom** [comment]
Thank you - can you reproduce the problem with the latest version?

**Comment by KlugFR** [comment]
The problem is slightly different with 0.5.15, no more sed error.

Debug and the mail show: ` DEVUSEP: /tmp/tmp.AjzxD MQvke` 
I guess this is the temporary mont path.

**Comment by grufocom** [comment]
So we are getting closer ;-)
0.5.16 should give you the used percent and not the mountpoint.
Could you please test this version!?

**Comment by KlugFR** [comment]
Unfortunately `df`doesn't support --output in CentOS6.

But I might have found a way: `df -hP` forces the output on one line.

It works at least with CentOS6, CentOS7, Ubuntu 18.04.

**Comment by grufocom** [comment]
changed it back and added "-P" flag to "df" command - please try it again!

**Comment by grufocom** [comment]
thanks a lot for debugging!
