### ISSUE TITLE
Wrong message: new Vee-Mail version available

### ISSUE THREAD

**Issue by blaze351** [grufocom/vee-mail#33]
If have updated to version 0.5.38. Now I always get the following message as last line in the e-mail: "Veeam Agent for Linux v5.0.2.4567, Vee-Mail Version 0.5.38 (new Vee-Mail version 0.5.38 available)".
Since 0.5.38 ist the latest version this seems to be wrong.

**Comment by grufocom** [comment]
hi blaze351,
please try the version 0.5.39 - should fix that bug!
regards
manfred

**Comment by blaze351** [comment]
hi manfred,
version 0.5.39 fixed it. thanks for this quick fix.
regards
blaze
