### ISSUE TITLE
Bug sed: -e Ausdruck #28, Zeichen 25: Nicht beendeter »s«-Befehl

### ISSUE THREAD

**Issue by ia4net** [grufocom/vee-mail#35]
root@xyz:/# /opt/vee-mail/vee-mail.sh
sed: -e Ausdruck #28, Zeichen 25: Nicht beendeter »s«-Befehl

**Comment by grufocom** [comment]
Bitte das debugging in der Config aktivieren und dann die gesamte Ausgabe schicken! :-)

**Comment by airlebnis0815** [comment]
I got the same error when running the script manually:
sed: -e expression #28, char 21: unterminated `s' command

The sent email is completely empty.

I removed 
`-e "s|XXXDISKSIZEXXX|$DEVSIZE|g" -e "s|XXXDISKUSEDXXX|$DEVUSED|g" -e "s|XXXDISKAVAILXXX|$DEVAVAIL|g" -e "s|XXXDISKUSEPXXX|$DEVUSEP|g"`
from vee-mail.sh Line 265 and now it is sending emails.

I'm running veeam 5.0.2.4567 on ubuntu server 20.04.4 and the backup destination is a Veeam Backup & Replication repository.

Debug output:
```
sudo /opt/vee-mail/vee-mail.sh
STARTTIME: 1657279870, ENDTIME: 1657280047, STATE: 6, JOBID: {cace2094-3325-4b35-9fbf-64fd600b02ed}
DETAILS: <ProgressDetails total_size="34357641216" total_used_size="15551717376" processed_data_size_bytes="17309892608" read_data_size_bytes="17309892608" transferred_data_size_bytes="5826291700" processing_speed="113266105" source_read_load="0" source_processing_load="18" network_load="0" target_write_load="49" network_throttling_enabled="false" repository_throttling_enabled="false" />
TARGET: , FST: , LOGIN: , DOMAIN:
PROCESSED: 16.1 GB, READ: 16.1 GB, TRANSFERRED: 5826291700
SPEED: 108.0, SOURCELOAD: 0, NETLOAD: 0, TARGETLOAD: 49
DURATION: 0:02:57, START: Friday, 08 July 2022 11:31:10, END: Friday, 08.07.2022 11:34:07, STIME: 11:31:10, ETIME: 11:34:07
ERRLOG:
HN: CALENDAR
STAT: Success
BGCOLOR: #00B050
START: Friday, 08 July 2022 11:31:10
SUCCESS: 1
ERROR: 0
WARNING: 0
STIME: 11:31:10
ETIME: 11:34:07
READ: 16.1 GB
TRANSFERRED: 5.4 GB
DURATION: 0:02:57
PROCESSED: 16.1 GB
BOTTLENECK: Target
ERRLOG:
SPEED: 108.0
TARGET:
FST:
LOGIN:
DOMAIN:
 DEVUSEP: Use%
0%
1%
46%
0%
0%
0%
100%
100%
100%
100%
100%
100%
100%
100%
0%
46%
sed: -e expression #28, char 21: unterminated `s' command
```

**Comment by grufocom** [comment]
could you please retrieve the dataset with your jobid from the sqlite database and send the output?

sqlite3 /var/lib/veeam/veeam_db.sqlite "SELECT a1.options FROM BackupRepositories AS a1 LEFT JOIN BackupJobs AS a2 ON a1.id=a2.repository_id WHERE a2.id='your JOBID' "

**Comment by airlebnis0815** [comment]
Output:
<VbrRepoOptions Version="1" VbrId="{d50bff65-b7a7-45de-831e-9f76eab6c0b9}" OrigName="Server@backy" />

**Comment by grufocom** [comment]
the reason might be the backup target!

due to the veeam repository, the actual backup target is missing here in the dataset, which is why the following can be read in the debug: "TARGET: , FST: , LOGIN: , DOMAIN:"

usually you will find an entry like this in the output of the dataset:
<OnShareRepositoryOptions Version="1" Address="192.168.1.1:/backup.nfs" FsType="nfs" Login="backupuser" Domain="" Password="password" Options="" />

I would probably have to take a closer look at the sqlite data sets to see if and how I can get sensible information out of them so that we can use it for the mail.

**Comment by grufocom** [comment]
close the issue due to lack of feedback

**Comment by andryyy** [comment]
Had the same problem, debugged it.

```
FST=$(mount | awk "\$3 ~ /^${AWKTARGET}\$/ {print \$5}")
FSD=$(mount | awk "\$3 ~ /^${AWKTARGET}\$/ {print \$1}")
```

These return:

```
root@p330tiny:/opt/vee-mail# mount | awk "\$3 ~ /^${AWKTARGET}\$/ {print \$5}"
autofs
ext4
root@p330tiny:/opt/vee-mail# mount | awk "\$3 ~ /^${AWKTARGET}\$/ {print \$1}"
systemd-1
/dev/sda1
```

The new line between the output is added by the ORS (Output Record Separator), that's what breaks the script for me. I modified the lines:

```
FST=$(mount | awk -vORS=" " "\$3 ~ /^${AWKTARGET}\$/ {print \$5}")
FSD=$(mount | awk -vORS=" " "\$3 ~ /^${AWKTARGET}\$/ {print \$1}")
```

That fixes it. I will add a PR, feel free to merge, ignore, close, or implement it any other way. :)

**Comment by grufocom** [comment]
thx, works for me too! :-)
