### ISSUE TITLE
[Feature Request] Healthchecks

### ISSUE THREAD

**Issue by Stonedestroyer** [grufocom/vee-mail#38]
Is it possible this script could be modified to work with healthchecks or similar APIs that take a HTTP request, as they are useful in ensuring that an email was sent. Healthchecks works with emails as well but doing it through CURL remains the email element.

**Comment by grufocom** [comment]
![Screenshot_20220912_132830](https://user-images.githubusercontent.com/24227479/189642682-baeff281-8ed5-40d5-9e04-f179828dca5e.png)

I have a service running which does monitor all jobs and shows statistics, you can also get a telegram message when there are failed jobs...

**Comment by Stonedestroyer** [comment]
I see, yeah I will close this then. I have something similar but the intent was not to rely on emails but curl but I guess you lose the information in the email.
