### ISSUE TITLE
Error after upgrading veeam from v5.0.2.4567 to v6.0.0.1060

### ISSUE THREAD

**Issue by blaze351** [grufocom/vee-mail#40]
After upgrading veeam from v5.0.2.4567 to v6.0.0.1060 the script produces the following error:
```
Error: in prepare, no such column: start_time (1)
/data/scripts/vee-mail.sh: line 193: [: -gt: unary operator expected
/data/scripts/vee-mail.sh: line 209: [: : integer expression expected
/data/scripts/vee-mail.sh: line 212: [: : integer expression expected
/data/scripts/vee-mail.sh: line 215: [: : integer expression expected
/data/scripts/vee-mail.sh: line 218: [: : integer expression expected
date: invalid date ‘@’
date: invalid date ‘@’
date: invalid date ‘@’
date: invalid date ‘@’
Failed to convert [023-02-1] to UUID.
```

**Comment by Thormir84** [comment]
I have the same errors.

**Comment by grufocom** [comment]
Please execute the following commands:
  /usr/bin/veeamconfig agreement acceptEula
  /usr/bin/veeamconfig agreement acceptThirdPartyLicenses
And try again!

**Comment by Thormir84** [comment]
> Please execute the following commands: /usr/bin/veeamconfig agreement acceptEula /usr/bin/veeamconfig agreement acceptThirdPartyLicenses And try again!

Nothing changed.

**Comment by spupuz** [comment]
i have the same error too

**Comment by grufocom** [comment]
veeam probably changed something in the data structure, i'll look into it and fix the problem!

**Comment by blaze351** [comment]
I have already accepted the licenses via GUI but run the commands anyway:
```
/usr/bin/veeamconfig agreement acceptEula
/usr/bin/veeamconfig agreement acceptThirdPartyLicenses
```

The error still exists:
```
Error: in prepare, no such column: start_time (1)
/data/scripts/vee-mail.sh: line 193: [: -gt: unary operator expected
/data/scripts/vee-mail.sh: line 209: [: : integer expression expected
/data/scripts/vee-mail.sh: line 212: [: : integer expression expected
/data/scripts/vee-mail.sh: line 215: [: : integer expression expected
/data/scripts/vee-mail.sh: line 218: [: : integer expression expected
date: invalid date ‘@’
date: invalid date ‘@’
date: invalid date ‘@’
date: invalid date ‘@’
Failed to convert [023-02-1] to UUID.
```

**Comment by grufocom** [comment]
please try the new version 0.5.45 - should fix the problem!

**Comment by Thormir84** [comment]
Now it works, but i receive this error:

Failed to convert [023-02-1] to UUID.

**Comment by blaze351** [comment]
> Now it works, but i receive this error:
> 
> Failed to convert [023-02-1] to UUID.

same here

**Comment by grufocom** [comment]
version 0.5.46 addresses this issue! :-)

**Comment by Thormir84** [comment]
Ok, now it works perfectly!

**Comment by grufocom** [comment]
thanks for testing and reporting back quickly!
