### ISSUE TITLE
Backup runs with errors b/c vee-mail script

### ISSUE THREAD

**Issue by Wackeljupp** [grufocom/vee-mail#42]
Maybe you can help.
Backup fails with executing the script:
Executing post-job script
      11:52:11         [error] Failed to perform backup
      11:52:11         [error] * Line 1, Column 1 Syntax error: Malformed token
      11:52:11         [error] Processing finished with errors at 2023-03-17 10:52:11 UTC

**Comment by grufocom** [comment]
Hi, do you have bash installed on your system?
Can you execute the vee-mail.sh script?

**Comment by Wackeljupp** [comment]
Yes bash is installed. i can run it finde. 
the error just comes when used as veeam post-backup script

**Comment by grufocom** [comment]
line 1, column 1 in the vee-mail.sh script would be the "#!/bin/bash" -> the "#" character...!

**Comment by Wackeljupp** [comment]
actuall i just run the script just as cron.
but i'll try to remove the #

**Comment by grufocom** [comment]
do not remove the "#" from the script!!!
if you run the script as a cron job, how can you get a post error message from veeam?

**Comment by Wackeljupp** [comment]
Hi Manfred.
Sorry for bothering you with that. 
The problem is/was not your great script....the problem is veeam itself and i can't get it to run again. I tried many things, nothing worked. So now i switched to borg again.
thank you for your work and keep up good work
