### ISSUE TITLE
/opt/vee-mail/vee-mail.sh: 15: [[: not found; 24: [: unexpected operator; 95: Bad substitution

### ISSUE THREAD

**Issue by Lucky-Lancer** [grufocom/vee-mail#44]
Hi, hab auf Linux Mint 21.1 veeam frisch installiert und würde gerne dein Skript nutzen für Mail Benachrichtigungen.
Veeam ist installiert und funktioniert, leider kommt beim Aufruf der vee-mail.sh nur folgende ausgabe:

stefan@Stefan-Mint:~$ sudo sh /opt/vee-mail/vee-mail.sh 
[sudo] Passwort für stefan:     
/opt/vee-mail/vee-mail.sh: 15: [[: not found
/opt/vee-mail/vee-mail.sh: 24: [: unexpected operator
/opt/vee-mail/vee-mail.sh: 95: Bad substitution

**Comment by grufocom** [comment]
Hi, das klingt für mich ein wenig danach als wäre hier keine bash im Einsatz.
Kannst du mal prüfen ob auf Linux Mint die bash installiert ist bzw. gegebenenfalls die bash nach installieren?!

**Comment by Lucky-Lancer** [comment]
Hi, die Bash ist installiert...
stefan@Stefan-Mint:~$ sudo apt-get install bash
[sudo] Passwort für stefan:     
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
bash ist schon die neueste Version (5.1-6ubuntu1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

**Comment by grufocom** [comment]
In Zeile 15 wird die effektive User ID abgefragt, normalerweise ist das bei root die 0.
Auf deinem System scheint die EUID irgendwie nicht gesetzt zu sein.
Kannst du mit "echo $EUID" prüfen, da sollte eine 0 daher kommen wenn du root bist.

**Comment by andryyy** [comment]
Er benutzt nicht die Bash sondern irgendeine Shell, die nur POSIX kompatible Anweisungen kennt. Da gibt es Dinge wie [[ nicht. 

Kannst die Datei als ausführbar markieren (chmod +x - das ist hier glaube ich sowieso notwendig) und dann sudo ./script.sh ausführen. 

Alternativ: sudo bash ./script.sh

**Comment by Lucky-Lancer** [comment]
Danke für eure Antworten:

wenn ch "echo $EUID" eingebe, ist die Ausgabe "1000"

mit dem befehl "sudo bash /opt/vee-mail/vee-mail.sh" funktioniert der Befehl jetzt tatsächlich - auch wenn ich keine Mail empfange...

stefan@Stefan-Mint:~$ cd /opt/vee-mail/
stefan@Stefan-Mint:/opt/vee-mail$ sudo bash vee-mail.sh 
[sudo] Passwort für stefan:     
STARTTIME: 1685298611, ENDTIME: 1685299818, STATE: 6, JOBID: {ca22e6d0-4633-4e77-adb3-1fdf55b9c687}, JOBNAME: Stefan-Mint-Veeam-Backup
DETAILS: <ProgressDetails total_size="256059113472" total_used_size="38399205376" processed_data_size_bytes="45563076608" read_data_size_bytes="45563076608" transferred_data_size_bytes="11324533456" processing_speed="48399685" source_read_load="0" source_processing_load="8" network_load="0" target_write_load="88" network_throttling_enabled="false" repository_throttling_enabled="false" />
TARGET: 192.168.9.91/backup, FST: smb, LOGIN: Backup, DOMAIN: nas1
PROCESSED: 42.4 GB, READ: 42.4 GB, TRANSFERRED: 11324533456
SPEED: 46.2, SOURCELOAD: 0, NETLOAD: 0, TARGETLOAD: 88
DURATION: 0:20:07, START: Sonntag, 28 Mai 2023 20:30:11, END: Sonntag, 28.05.2023 20:50:18, STIME: 20:30:11, ETIME: 20:50:18
ERRLOG: 
HN: STEFAN-MINT
STAT: Success
BGCOLOR: #00B050
START: Sonntag, 28 Mai 2023 20:30:11
SUCCESS: 1
ERROR: 0
WARNING: 0
STIME: 20:30:11
ETIME: 20:50:18
READ: 42.4 GB
TRANSFERRED: 10.5 GB
DURATION: 0:20:07
PROCESSED: 42.4 GB
BOTTLENECK: Target
ERRLOG: 
SPEED: 46.2
TARGET: 192.168.9.91/backup
FST: smb
LOGIN: Backup
DOMAIN: nas1
 DEVUSEP: 38%

**Comment by grufocom** [comment]
Wenn die EUID auf 1000 ist, dann hast du das Script nicht als root-User ausgeführt!
Das ist zwingend nötig damit die Zugriffe klappen, der User mit der ID 1000 braucht sudo beim Aufruf.
In Sachen Mail kommt es darauf an ob du alle Werte in der Config korrekt eingegeben hast, die Ausgabe oben zeigt ja dass mit dem sudo alle Daten korrekt ausgelesen wurden - soweit sieht das gut aus.

**Comment by Lucky-Lancer** [comment]
Stimmt, Asche auf mein Haupt. Mit Sudo Rechten EUID ist bei mir auch 0.
Danke, ich muss meine Konfig wohl nochmal prüfen. Es genügt aber die Konfig anzupassen, sendmail habe ich einfach nur installiert, oder?

**Comment by grufocom** [comment]
Ja, es sollte reichen die Config anzupassen. Sendmail oder alternativ mit curl. Bei letzterem hat man den Vorteil dass das lokale Systeme nicht korrekt für den Mailversand konfiguriert sein muss weil der Versand direkt über den Mailserver erfolgt.
