### ISSUE TITLE
Kein Mailversand - Problem mit $TEMPFILE

### ISSUE THREAD

**Issue by Lucky-Lancer** [grufocom/vee-mail#45]
Hallo,

nachdem ich das Skript erfolgreich ausführen kann, erhalte ich leider keine Mail. Ich nutze Curl.
Ich habe im Skript die Curl Zeile durch geprüft und die Mail kommt an, solange ich als "-upload-file" eine test.txt nutze. 
Sobald die $TEMPFILE Variable ins Spiel kommt, erhalte ich keine Mail mehr.
Wenn ich im Skript echo $TEMPFILE ausgeben lasse und das "rm $TEMPFILE" entferne, erhalte ich einen Pfad "/tmp/tmp.4tvRKnyZQF"
Hier ist auch der E-Mail Body hinterlegt der gut aussieht. 
Hier die Datei - für den Upload hier habe ich .TXT ergänzt
[tmp.4tvRKnyZQF.TXT](https://github.com/grufocom/vee-mail/files/11714351/tmp.4tvRKnyZQF.TXT)

Hier die Ausgabe des Terminals inkl. Debug aktiviert.

stefan@Stefan-Mint:~$ cd /opt/vee-mail/
stefan@Stefan-Mint:/opt/vee-mail$ sudo bash vee-mail.sh
[sudo] Passwort für stefan:     
STARTTIME: 1685903412, ENDTIME: 1685904231, STATE: 6, JOBID: {ca22e6d0-4633-4e77-adb3-1fdf55b9c687}, JOBNAME: Stefan-Mint-Veeam-Backup
DETAILS: <ProgressDetails total_size="256059113472" total_used_size="49347076096" processed_data_size_bytes="56791228416" read_data_size_bytes="56791228416" transferred_data_size_bytes="9107451712" processing_speed="96146809" source_read_load="0" source_processing_load="36" network_load="0" target_write_load="79" network_throttling_enabled="false" repository_throttling_enabled="false" />
TARGET: 192.168.9.91/backup, FST: smb, LOGIN: Backup, DOMAIN: nas1
PROCESSED: 52.9 GB, READ: 52.9 GB, TRANSFERRED: 9107451712
SPEED: 91.7, SOURCELOAD: 0, NETLOAD: 0, TARGETLOAD: 79
DURATION: 0:13:39, START: Sonntag, 04 Juni 2023 20:30:12, END: Sonntag, 04.06.2023 20:43:51, STIME: 20:30:12, ETIME: 20:43:51
ERRLOG: 
HN: STEFAN-MINT
STAT: Success
BGCOLOR: #00B050
START: Sonntag, 04 Juni 2023 20:30:12
SUCCESS: 1
ERROR: 0
WARNING: 0
STIME: 20:30:12
ETIME: 20:43:51
READ: 52.9 GB
TRANSFERRED: 8.5 GB
DURATION: 0:13:39
PROCESSED: 52.9 GB
BOTTLENECK: Target
ERRLOG: 
SPEED: 91.7
TARGET: 192.168.9.91/backup
FST: smb
LOGIN: Backup
DOMAIN: nas1
 DEVUSEP: 38%
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  218k    0     0  100  218k      0   473k --:--:-- --:--:-- --:--:--  474k
/tmp/tmp.4tvRKnyZQF

**Comment by grufocom** [comment]
Hallo Stefan, kannst du die Zeile im Script mit dem curl Kommando mal kopieren und mit einem echo versehen damit wir sehen was genau in deinem Fall aufgerufen wird?!
Schöne Grüße
Manfred

**Comment by Lucky-Lancer** [comment]
Hallo Manfred,
ich habe die Curl Zeile mit echo versehen, hier die Ausgabe.
Schaut an und für sich gut aus, das Skript würde gerne die /tmp Datei verschicken, aber es macht es nicht.
Tausche ich im Skript die Variable aus und setze da eine Text.txt ein, kommt die Mail damit an.


stefan@Stefan-Mint:~$ cd /opt/vee-mail/
stefan@Stefan-Mint:/opt/vee-mail$ sudo bash vee-mail.sh 
[sudo] Passwort für stefan:     
STARTTIME: 1685903412, ENDTIME: 1685904231, STATE: 6, JOBID: {ca22e6d0-4633-4e77-adb3-1fdf55b9c687}, JOBNAME: Stefan-Mint-Veeam-Backup
DETAILS: <ProgressDetails total_size="256059113472" total_used_size="49347076096" processed_data_size_bytes="56791228416" read_data_size_bytes="56791228416" transferred_data_size_bytes="9107451712" processing_speed="96146809" source_read_load="0" source_processing_load="36" network_load="0" target_write_load="79" network_throttling_enabled="false" repository_throttling_enabled="false" />
TARGET: 192.168.9.91/backup, FST: smb, LOGIN: Backup, DOMAIN: nas1
PROCESSED: 52.9 GB, READ: 52.9 GB, TRANSFERRED: 9107451712
SPEED: 91.7, SOURCELOAD: 0, NETLOAD: 0, TARGETLOAD: 79
DURATION: 0:13:39, START: Sonntag, 04 Juni 2023 20:30:12, END: Sonntag, 04.06.2023 20:43:51, STIME: 20:30:12, ETIME: 20:43:51
ERRLOG: 
HN: STEFAN-MINT
STAT: Success
BGCOLOR: #00B050
START: Sonntag, 04 Juni 2023 20:30:12
SUCCESS: 1
ERROR: 0
WARNING: 0
STIME: 20:30:12
ETIME: 20:43:51
READ: 52.9 GB
TRANSFERRED: 8.5 GB
DURATION: 0:13:39
PROCESSED: 52.9 GB
BOTTLENECK: Target
ERRLOG: 
SPEED: 91.7
TARGET: 192.168.9.91/backup
FST: smb
LOGIN: Backup
DOMAIN: nas1
 DEVUSEP: 38%
/usr/bin/curl --ssl-reqd smtp://mein-smtp-server.de:25 --mail-from sender@meine-domain.de --mail-rcpt stefan@meine-domain.de --upload-file /tmp/tmp.fJFdgnzY39 --user Mein-User:MeIn-Password

**Comment by grufocom** [comment]
Wie sehen denn die Rechte auf der temp-Datei aus?
Das wäre jetzt das einzige was mir einfällt was hier noch Probleme machen könnte.

**Comment by Lucky-Lancer** [comment]
Schaut gut aus, das Skript läuft als Sudo, mit den rechten ist in Temp eigentlich ja alles erlaubt...

-rw-------  1 root   root   223300 Jun 11 18:41 tmp.fJFdgnzY39

![Bildschirmfoto vom 2023-06-11 19-25-37](https://github.com/grufocom/vee-mail/assets/11034960/14d53149-f173-48a8-bbc2-0d0f3c0d6658)

**Comment by grufocom** [comment]
Da bin ich jetzt auch ein wenig überfragt warum es bei dir nicht funktioniert - technisch scheint da eigentlich alles in Ordnung zu sein. Du führst das Script auf der CLI aus oder - nicht als Post-Script?

**Comment by Lucky-Lancer** [comment]
Da ich noch am Testen bin, führe ich die Datei aktuell noch manuell aus dem Terminal aus.

**Comment by grufocom** [comment]
-sS steht für silent & show errors

**Comment by Lucky-Lancer** [comment]
ah, silent, daher erfolgt keine Ausgabe ;)

**Comment by grufocom** [comment]
Hallo Stefan,

ich habe gerade eine frische Installation von Linux Mint durchgeführt, alle Updates installiert, Veeam Agent für Linux installiert, git; sqlite3; curl installiert, die vee-mail.config korrekt mit den Daten für den Mailversand via curl eingerichtet und anschließend ein Backup gestartet und vee-mail.sh aufgerufen.

Das Ergebnis sieht wie folgt aus:

![image](https://github.com/grufocom/vee-mail/assets/24227479/c528e7d6-03fa-4470-be36-627bfe382bb5)

Also hat auf Anhieb alles einwandfrei funktioniert!

Schöne Grüße
Manfred

**Comment by grufocom** [comment]
Tja, das Problem mit den Versionsnummern :-)
3.7 ist niedriger als 3.37 weil hier 37 mit 7 verglichen wird...

meine History sagt folgendes:

```
dpkg -i veeam-release-dev_1.0.8_amd64.deb
apt update
apt dist-upgrade
apt install veeam
apt install sqlite3 curl git
cd /tmp
git clone https://github.com/grufocom/vee-mail
mv vee-mail /opt/
cd /opt/vee-mail/
vi vee-mail.config
veeam
./vee-mail.sh
```

und schon war das Mail in meiner Mailbox...

Linux Mint 21.1 Vera

Also viel mehr fällt mir jetzt nicht mehr ein!

Schöne Grüße
Manfred

**Comment by Lucky-Lancer** [comment]
Hallo Manfred,

jetzt geht es bei mir auch! 
Ich verstehe es zwar nicht, aber ich schildere mal was ich jetzt anders gemacht habe:

Zuvor habe ich die Dateien aus deinem Git-Repo manuell heruntergeladen und in /opt/vee-mail abgelegt. 
Jetzt habe ich git nachinstalliert und es über deinen befehlt erst nach /tmp heruntergeladen und dann nach /opt/ verschoben.
Dann meine bestehende vee-mail.config wieder in /opt/vee-mail/ verschoben und überschrieben. Hier ist also kein Unterschied drin.

Dann vee-mail.sh ausgeführt und schwubbs war die Mail da!

Folgende unterschiede sind mir aufgefallen:
Im Ordner /opt/vee-mail/ gibt es noch einen versteckten Ordner .git, aber auch wenn ich diesen lösche geht die Mail noch...
Daher ist eigenltich alles genauso wie zuvor, nur dass ich es über den git Befehl heruntergeladen habe und nicht manuell aus dem Browser.

Gibt es hierfür eine Erklärung, wo da der unterschied sein soll? 

Aber auf jeden Fall geht es jetzt und die Freude ist groß, vielen Dank dir für die Unterstützung und deine Mühen!

Beste Grüße,
Stefan
