### ISSUE TITLE
Kein E-Mail-Versand

### ISSUE THREAD

**Issue by tualatin** [grufocom/vee-mail#47]
Hin und wieder habe ich das Problem, das keine Mails versendet werden. In unregelmäßigen, regelmäßigen Abständen erfolgt kein E-Mail Versand, obwohl das Backup gelaufen ist, mittlerweile kann ich schon fast sagen, zwei Backups läuft alles wie gehabt, spätestens beim vierten lief das Backup zwar, aber es wurde keine Mail rausgeschickt. In dem Skript gibt es die Variable
```
SENDM=0
```
die an unterschiedlichen Stellen auf 1 gesetzt wird. Ich habe sie zum Testen global auf eins gesetzt und bekomme jetzt immer eine Benachrichtigung per E-Mail. Allerdings wird manchmal nur das Template, ohne weitere Werte, versendet, daß werden wahrscheinlich die sein Zustände sein, wo sonst keine Mail verschickt wird. Schaue ich in das Backup rein, lief es durch.

Hat jemand eine Idee, woran das liegen könnte?

**Comment by grufocom** [comment]
Hi tualatin,
erhöhe mal die SLEEP Zeit in der Config - dann wird vor dem Versand länger gewartet.
Schöne Grüße
Manfred

**Comment by redberry94** [comment]
Hab das selbe Problem seit heute morgen, bei mir geht allerdings keine Mail raus ohne das ich was an der Konfiguration (oder dem Server an sich) etwas geändert hätte?

Viele Grüße
Florian

**Comment by grufocom** [comment]
Hallo Florian,
hast du an der SLEEP Einstellung in der Config schon gedreht?
Schöne Grüße
Manfred

**Comment by redberry94** [comment]
Hey Manfred, 

ja hatte es testweise aus 120 Sekunden gestellt. Hatte mir auch https://github.com/grufocom/vee-mail/issues/45 durchgelesen und die Stepps probiert. 

Es hat bis heute auch tadellos funktioniert? In welchem Verzeichnis wird das tempfile geschrieben? Hatte testweise mal den rm Befehl raus genommen und kein tempfile gefunden? 

Viele Grüße
Florian

**Comment by grufocom** [comment]
Hallo Florian,
das TEMPFILE wird mit "mktemp" erzeugt - je nachdem wie dein System tickt landest das dann eventuell in einem anderen Verzeichnis - gewöhnlich aber in /tmp/
Wenn du das debugging aktiviert hast müsstest du im Syslog auch Einträge finden - Suchbegriff "vee-mail"
Schöne Grüße

**Comment by redberry94** [comment]
Hallo Manfred, 

solangsam gehen mir die Ideen aus. Tempfile wird erzeugt und im syslog steht auch nichts was auf Fehler hindeutet?  

ich bin der Sache aber näher gekommen: Das Skriupt erzeugt für mich folgendes Tempfile: 

```
From: no-reply@domain.de
To: mail@domain.de
Subject: =?UTF-8?Q?[Success] SRV-HOME.DOMAIN.DE - Monday, 16 October 2023 07:09:44?=
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit
```

Wenn `=?UTF-8?Q?` am Anfang der Subject Zeile und `?=` am Ende der Zeile entferne kommt die Mail an. Soll das aus deiner Sicht da stehen? 

Viele Grüße
Florian

**Comment by grufocom** [comment]
Hab den Betreff jetzt in der aktuellen Version auf base64 umgestellt, kannst du das mal testen ob es damit bei dir wieder klappt!?

**Comment by redberry94** [comment]
> Das könnte man schon umstellen, die Frage ist aber wohl eher warum das von gestern auf heute auftritt. Da muss ja vermutlich beim Mailserver was geändert worden sein - steht der unter deiner Kontrolle oder ist das ein externer Service?

Ja das fand ich auch sehr irritierend. Nein hab da kein Zugriff drauf, ist ein SaaS Produkt. Ich hätte dich sonst gern mit mehr Infos versorgt. 

> Hab den Betreff jetzt in der aktuellen Version auf base64 umgestellt, kannst du das mal testen ob es damit bei dir wieder klappt!?

Damit klappt es perfekt, vielen Dank!

**Comment by grufocom** [comment]
Super, danke für's Feedback!
