### ISSUE TITLE
multiple destination addreses

### ISSUE THREAD

**Issue by borjaevo** [grufocom/vee-mail#48]
Hello, i tried to add more than one address into the EMAILTO var but its not working. I tried to do a workaround cloning vee-mail.sh and vee-mail.config and changing the EMAILTO var for the second script. Next, i create a script "main" to execute both .sh sequentially like:
`vee-mail.sh && vee-mail2.sh`
this works sometimes and sometimes not. And don't know why. Any ideas?

**Comment by grufocom** [comment]
Hi, you could try to modify the vee-mail.sh script and add your second mail address with the "--mail-rcpt" command line parameter of curl to the line startet with "$CURL" at the end of the script.

**Comment by borjaevo** [comment]
> Hi, you could try to modify the vee-mail.sh script and add your second mail address with the "--mail-rcpt" command line parameter of curl to the line startet with "$CURL" at the end of the script.

This worked well :)

**Comment by grufocom** [comment]
Thank you for your feedback!
In a future version I will include that feature to add more than one email address.
