### ISSUE TITLE
0.5.17 disk used/avail dont seem to work anymore

### ISSUE THREAD

**Issue by akurz42** [grufocom/vee-mail#5]
I've updated from 0.5.12 to 0.5.17 and found that for my NFS backup target the fields Disk used, Disk avail, and Disk used % are empty. This used to work with 0.5.12.

Also the update check says "Vee-Mail Version 0.5.17 (new Veeam-Mail version 0.5.16 available)", which is purely cosmetic, obviously.

Running on Debian Buster 10.5 (2 Proxmox PVE Servers)

Regards,
Alex

**Comment by grufocom** [comment]
Hi Alex,

could you send me the output of your "mount" command when your nfs share is mounted?
Wrong Version should be fixed - forgot to update on my server! ;-)

Regards,
Manfred

**Comment by akurz42** [comment]
Not sure where to find exact info on that. Veeam mounts the NFS backup target on demand. I've pulled this out of syslog:

`Sep 14 04:30:01 pve01 CRON[8502]: (root) CMD (veeamconfig job start --id {d79d0234-3741-4650-9cd1-c12d39cdd28a} --retriable --scheduled --highpriority /dev/null)`
`Sep 14 04:30:06 pve01 kernel: [191823.509580] EXT4-fs (veeamimage0): mounted filesystem with ordered data mode. Opts: (null)`
`Sep 14 04:30:06 pve01 systemd[1]: tmp-\x7b4142490b\x2d2007\x2d4429\x2dac94\x2dda67ca1410a2\x7d.mount: Succeeded.`
`Sep 14 04:30:25 pve01 systemd[1]: tmp-tmp.HxEqNlEqiz.mount: Succeeded.`
`Sep 14 04:30:25 pve01 systemd[1]: tmp-veeam-192.168.123.99:volume2backup_pve_srv.mount: Succeeded.`
`Sep 14 04:30:56 pve01 systemd[1]: tmp-tmp.QqUOrUYOk8.mount: Succeeded.`


`192.168.123.99:/volume2/backup_pve_srv` is my backup-target. I've also attached two screenshots showing what the backup-target section looked like before and after the update.

0.5.12:
![0 15 12](https://user-images.githubusercontent.com/26791618/93117158-b343b700-f6be-11ea-98be-0efb599b5326.PNG)

0.5.17:
![0 5 17](https://user-images.githubusercontent.com/26791618/93117160-b3dc4d80-f6be-11ea-831c-6747cf2a5a9b.PNG)

I've also "fixed" the version check issue by changing this line:
`if [ ! "$VERSION" == "$AKTVERSION" ]; then`

to this:
`if [ ! "$VERSION" -ge "$AKTVERSION" ]; then`

This should allow for "lazier" updating of your server version :)

Thanks,
Alex

**Comment by grufocom** [comment]
Hi Alex,

the " -ge " will only work with numeric expressions, the version number 0.5.17 is not numeric.
If I remove the "." from the string it would work - and then " -le " would be the better choice I think.

Please mount your nfs share manually to any mount-point and send me the output of the following command:
df -hP|grep "/volume2/backup_pve_srv"

Thank you
Manfred

**Comment by akurz42** [comment]
Here you go:
`192.168.123.99:/volume2/backup_pve_srv   11T  6.3T  4.6T  58% /mnt/test`

Seems all good.

And big Oops! on the "-ge". No idea what I was thinking there :)

Alex

**Comment by grufocom** [comment]
That should work!
Could you please download the latest version (if not already done), activate DEBUG=1 in the config file and send me the debug output from your syslog file. (grep "vee-mail" /var/log/syslog)
Thank you
Manfred

**Comment by akurz42** [comment]
Just updated to 0.5.19. The fields are still empty (and quite a few other things actually got worse - more below)

Here's the log:
`Sep 16 09:43:20 pve02 vee-mail: waiting for 30 seconds`
`Sep 16 09:43:50 pve02 vee-mail: STARTTIME: 1600242151, ENDTIME: 0, STATE: 1, JOBID: {4b66eede-c9a2-43a0-8540-5502e974b21c}\nDETAILS: <ProgressDetails total_size="499566772224" total_used_size="21802594304" processed_data_size_bytes="21802594304" read_data_size_bytes="8698986496" transferred_data_size_bytes="22265189" processing_speed="598279676" source_read_load="62" source_processing_load="71" network_load="0" target_write_load="58" network_throttling_enabled="false" repository_throttling_enabled="false" />`
`Sep 16 09:43:50 pve02 vee-mail: TARGET: 192.168.123.99:/volume2/backup_pve_srv, FST: nfs, LOGIN: , DOMAIN:`
`Sep 16 09:43:50 pve02 vee-mail: PROCESSED: 20.3 GB, READ: 8.1 GB, TRANSFERRED: 22265189`
`Sep 16 09:43:50 pve02 vee-mail: SPEED: 570.5, SOURCELOAD: 62, NETLOAD: 0, TARGETLOAD: 58`
`Sep 16 09:43:50 pve02 vee-mail: DURATION: 15:17:29, START: Wednesday, 16 September 2020 09:42:31, END: Thursday, 01.01.1970 01:00:00, STIME: 09:42:31, ETIME:
01:00:00`
`Sep 16 09:43:50 pve02 vee-mail: ERRLOG:`
`Sep 16 09:43:50 pve02 vee-mail: HN: PVE02; STAT: ; BGCOLOR: ; START: Wednesday, 16 September 2020 09:42:31; SUCCESS: 0; ERROR: 0; WARNING: 0; STIME: 09:42:31; ETIME: 01:00:00; READ: 8.1 GB; TRANSFERRED: 21 MB; DURATION: 15:17:29; PROCESSED: 20.3 GB; BOTTLENECK: Source CPU; ERRLOG: ; SPEED: 570.5; TARGET: 192.168.123.99:/volume2/backup_pve_srv; FST: nfs; LOGIN: ; DOMAIN: ;  DEVUSEP:`

As to what became worse:
Subject (old): [Success] PVE02 - Wednesday, 16 September 2020 05:00:01
Subject (new): [] PVE02 - Wednesday, 16 September 2020 09:42:31

As a follow-up issue to the fact that success/fail is not known, the design of the mail (green background, red background) is off as well (all white).

Alex

**Comment by grufocom** [comment]
What irritates me a bit is the "STATE: 1", STATE should be 6 for SUCCESS, 7 for ERROR and 9 for WARNING.
Which state does the veeam command show for that job?

**Comment by akurz42** [comment]
Yeah, strange, isnt it. Veeam shows this:
 pve02                                                                                  Success         2020-09-16 09:42:31   2020-09-16 09:43:50

**Comment by akurz42** [comment]
Full status:
` Backup                                                              100%                                                             Status: Success



     Summary                              Data

     Duration:           00:01:19         Processed:          20.3 GB (100%)
     Processing rate:    570.6 MB/s       Read:               8.1 GB
     Bottleneck:         Agent            Transferred:        21.2 MB (390.7x)

      Time             Action                                                                                                                 Duration

      09:42:31         Job pve02 started at 2020-09-16 09:42:31 GMT
      09:42:38         Preparing to backup
      09:42:48         Creating volume snapshot                                                                                               00:00:02
      09:42:51         Starting incremental backup to Repository_1
      09:42:56         Backed up pve 8.1 GB at 827.9 MB/s                                                                                     00:00:10
      09:43:06         Backing up summary.xml                                                                                                 00:00:00
      09:43:09         Releasing snapshot                                                                                                     00:00:02
      09:43:11         Applying retention policy                                                                                              00:00:08
      09:43:11         Full backup file merge completed successfully                                                                          00:00:07
      09:43:19         Executing post-job script
      09:43:50         Post-job script has been executed successfully
      09:43:50         Processing finished at 2020-09-16 09:43:50 GMT`

**Comment by grufocom** [comment]
I think veeam backup job was not finished completely at the moment the script ran!

Sep 16 09:43:20 pve02 vee-mail: waiting for 30 seconds
Sep 16 09:43:50 pve02 vee-mail: STARTTIME: 1600242151, ENDTIME: 0

I will have to change the value from 30 to 60 seconds... (version 0.5.20) give me a minute.

**Comment by akurz42** [comment]
Take two :)

**Comment by akurz42** [comment]
No change, unfortunately. Exactly the same effect as 0.5.19.

Alex

**Comment by grufocom** [comment]
I think I've found the problem, but it's a bit weird - one space too much in front of the "df" has probably caused this problem. I've now only corrected the indentations and it works for me again. Please test Version 0.5.21!

**Comment by akurz42** [comment]
Getting better! Backup Target stats are working again, status isn't.
![veeam03](https://user-images.githubusercontent.com/26791618/93323023-565a1500-f814-11ea-99a1-59a2205f0072.PNG)

**Comment by grufocom** [comment]
Switch back from DEBUG=1 to DEBUG=0 and try again please!
If it works without debug I know what to change. :-)

**Comment by akurz42** [comment]
Nope, that's not it. I already switched back to 0 right after pulling the log. Had one too many machines run out of space because I forgot resetting debug logging :)

**Comment by akurz42** [comment]
Just tested on my second host - same behaviour.

Alex

**Comment by grufocom** [comment]
Thanks for the info, already helps!
The script blocks the veeam service without background mode because it is waiting for the post-script.
Version 0.5.22 should fix that.

**Comment by akurz42** [comment]
All working 100% with 0.5.22. No further problems to report.

Top job!

Ah actually there's one thing: 
The line `logger -t vee-mail "new Veeam-Mail version $AKTVERSION available"`
should probably say "Vee-Mail" instead of "Veeam-Mail" :)

Thanks for the tool & the quick fix!

Alex

**Comment by grufocom** [comment]
Great - thank you for debugging and reporting!
I'll fix that line without releasing a new version :-)
