### ISSUE TITLE
0.5.17: Execution as Post-Script does not work anymore

### ISSUE THREAD

**Issue by MrzJkl** [grufocom/vee-mail#6]
If i run the script as Post-Job-Script, i get the following result: (No Warning/Success/Failure)

![Screenshot 2020-09-14 194657](https://user-images.githubusercontent.com/38078338/93120318-7928e400-f6c3-11ea-9c84-afe926a8a823.png)

If i run the Script manually i get a normal result.

**Comment by grufocom** [comment]
Hi, could you please execute the following command and post the details:

`sqlite3 /var/lib/veeam/veeam_db.sqlite  "select start_time, end_time, state, progress_details, job_id from JobSessions order by start_time DESC limit 1;"
`
Regards,
Manfred

**Comment by MrzJkl** [comment]
1600146001|1600147902|6|<ProgressDetails total_size="1000202043392" total_used_size="291418083328" processed_data_size_bytes="311159382016" read_data_size_bytes="311159382016" transferred_data_size_bytes="186537806" processing_speed="165977341" source_read_load="88" source_processing_load="20" network_load="0" target_write_load="20" network_throttling_enabled="false" repository_throttling_enabled="false" />|{0c651a8e-1a62-48dc-9c44-bbdd316928eb}

**Comment by grufocom** [comment]
State 6 (3rd field) is SUCCESS so that's ok.
I added more debugging in version 0.5.18 - please download and install this version.
Then set DEBUG=1 in the config file and start the backup process again.

Could you post the output of 
`grep vee-mail /var/log/syslog`
after the script has run!?

**Comment by MrzJkl** [comment]
Backup is working fine. I suggest, the job has no "really finished" at the execution time of the script as post-job-script. Maybe the data above from the sqlite-database is not complete at execution time. Is that possible?

**Comment by MrzJkl** [comment]
> Could you post the output of
> `grep vee-mail /var/log/syslog`
> after the script has run!?

Do you mean after the post-job-execution or a manual run?

**Comment by MrzJkl** [comment]
Ok, i thinks thats i problem. Ill deactivate the debug-mode and try it again. I´ll post a sitrep tomorrow.

**Comment by grufocom** [comment]
perfect - thank you!

**Comment by grufocom** [comment]
version 0.5.19 got another important change, it will check if it is started from veeam and pause for 30 seconds.

**Comment by MrzJkl** [comment]
Faster update schedule than Mozilla Firefox 😂😂😂

**Comment by grufocom** [comment]
the script is one track smaller than firefox :-)

**Comment by MrzJkl** [comment]
But only one little track...

Script works fine with disabled debug-Mode. Great! 

Thank you for your time!

Great work btw! 💖

**Comment by grufocom** [comment]
nice to hear, thanks for testing and reporting the problem! :-)
