### ISSUE TITLE
Central reporting

### ISSUE THREAD

**Issue by KlugFR** [grufocom/vee-mail#7]
Hello.

More of a suggestion than an issue.

I found this: https://github.com/st3root/VeeamFreeAgentDashboard

Could it (rewritten maybe) be an addon to vee-mail?
Or maybe a dual mode for vee-mail (sending mail like it does today vs writing to a central API/DB to display results on a web page)?

**Comment by grufocom** [comment]
i have already built a similar service and plan to offer it for small installations as a free service and from a certain number of hosts for a fee!
![Screenshot_20200915_173955](https://user-images.githubusercontent.com/24227479/93232897-b69c7880-f77a-11ea-9168-c03a4effa4cc.png)

**Comment by grufocom** [comment]
if you are interested i can give you a free access for three hosts
