### ISSUE TITLE
Script launch as post-script => Not complete

### ISSUE THREAD

**Issue by herken** [grufocom/vee-mail#8]
Hello,

i configured Veeam ton execute the script at the end of the backup but in this case, it's not complete with color, success message 
![image](https://user-images.githubusercontent.com/36696910/93348470-89ad9b80-f836-11ea-9c34-a4b7bad15ff8.png)

If i launch the vee-mail.sh manually : 
![image](https://user-images.githubusercontent.com/36696910/93348587-b19cff00-f836-11ea-830e-e76fa7218884.png)

I tried using the cron but never work and i think it's better to launch it from veam to have the report directly at the end.

Any idea? Thank you.

**Comment by grufocom** [comment]
Please install the Version 0.5.22 - should be ok with that version!

**Comment by herken** [comment]
Working with 0.5.22, thank you !

**Comment by grufocom** [comment]
Great to hear - thank you for your feedback!
