### ISSUE TITLE
Notification Log Level

### ISSUE THREAD

**Issue by fmosergit** [grufocom/vee-mail#9]
Hello,
I would really appreciate a feature where i can specify the log level for notification mails. (e.g only send mail on error or warning log level and not on success log level)
Regards

**Comment by unevenit** [comment]
+Upvote for this, i need this too.

**Comment by MrzJkl** [comment]
+Upvote, this would be great. 

@grufocom Maybe i can implement this.

**Comment by grufocom** [comment]
could you please try the latest version and give me a feedback!

**Comment by unevenit** [comment]
It doesnt work like the typical standards. 
I Added a Pull request for common loglevel standards 

@grufocom Maybe you can Merge this.

**Comment by grufocom** [comment]
Merged and fixed!
